give @p pa:acacia_log_armor
give @p pa:andesite_armor
give @p pa:diorite_armor
give @p pa:dirt_armor
give @p pa:cobblestone_armor
give @p pa:birch_log_armor
give @p pa:jungle_tree_log_armor
give @p pa:birch_leaves_armor
give @p pa:dark_oak_log_armor
give @p pa:oak_leaves_armor
give @p pa:arma_de_piedra
give @p pa:spruce_log_armor
give @p pa:birch_wooden_planks_armor
give @p pa:oak_wooden_planks_armor
give @p pa:spruce_wooden_planks_armor
give @p pa:sea_armor
give @p pa:sponge_armor
give @p pa:jungle_tree_wooden_planks_armor
give @p pa:fire_armor
give @p pa:acacia_wooden_planks_armor
give @p pa:dark_oak_wooden_planks_armor
give @p pa:warped_stem_armor
give @p pa:glowstone_armor
give @p pa:cactus_armor
give @p pa:skeleton_armor
give @p pa:slime_armor
give @p pa:spruce_leaves_armor
give @p pa:blackstone_armor
give @p pa:jungle_tree_leaves_armor
give @p pa:bedrock_armor
give @p pa:obsidian_armor
give @p pa:endstone_armor
give @p pa:blackstone_armor2
give @p pa:ice_armor
give @p pa:glass_armor
give @p pa:hay_bale_armor
give @p pa:emeral_armor
give @p pa:oak_log_armor
give @p pa:grenite_armor
give @p pa:crimson_stem_armor
give @p pa:netherra_armor
give @p pa:acac_leaves_armor
give @p pa:obsidia_sword
give @p pa:sea_axe
give @p pa:emerald_sworld
give @p pa:fire_hammer
give @p pa:bedrock_sword
